language: bash
dist: bionic
services:
 - docker
before_install:
  - sudo rm -rf /var/lib/apt/lists/*
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) edge"
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce qemu-user-static
  - mkdir -vp ~/.docker/cli-plugins/
  - curl --silent -L "https://github.com/docker/buildx/releases/download/v0.4.2/buildx-v0.4.2.linux-amd64" > ~/.docker/cli-plugins/docker-buildx
  - chmod a+x ~/.docker/cli-plugins/docker-buildx
script:
  - docker buildx create --use
  - docker context ls
  - docker buildx build --platform linux/arm/v7,linux/arm64/v8,linux/amd64 --tag jacobalberty/unifi:multiarch .
  - docker run -d -p 8443:8443 -p 8080:8080 -e RUNAS_UID0=true --name unifi jacobalberty/unifi:multiarch
  - docker ps | grep -q unifi
  - docker logs unifi
  - sleep 10 && curl --connect-timeout 5 --max-time 10 --retry 5 --retry-delay 0 --retry-max-time 60 -kILs --fail http://127.0.0.1:8080 || exit 1
